
services:

    #####################################################################################
    # Services build
    #####################################################################################
    sps-service:
      image: ${IMAGE:-ghcr.io/mind-wrap/sps-service:dev}
      container_name: sps-service
      build:
          context: .
          target: release
      env_file: ./.env.production
      ports:
          - '5001:5001'
      networks:
          - sps-network

networks:
  sps-network:
    name: sps-network